DROP TABLE TB_USER;

CREATE TABLE TB_USER
(
    USER_ID VARCHAR2(30) ,
    PASSWORD VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH DATE,
    GENDER CHAR,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(50),
    NICKNAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30),
    CREATE_ACCOUNT_DATE DATE DEFAULT SYSDATE,
    DELETE_ACCOUNT_YN CHAR DEFAULT 'N' CHECK(DELETE_ACCOUNT_YN IN ('Y','N')) NOT NULL,
    IS_ADMIN VARCHAR2(10) DEFAULT 'USER' CHECK(IS_ADMIN IN ('ADMIN','USER')),
    GRADE VARCHAR2(10) DEFAULT 'SILVER',
    USER_IMG VARCHAR2(500),
    USER_INFO VARCHAR2(1000),
    
    CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID)
);  

