DROP TABLE SITTER_REVIEW;
DROP TABLE FREEMARKET_REVIEW;
DROP TABLE SITTER;
DROP TABLE FREEMARKET;
DROP SEQUENCE SEQ_SITTER;
DROP SEQUENCE SEQ_SITTER_REVIEW;
DROP SEQUENCE SEQ_FREEMARKET;
DROP SEQUENCE SEQ_FREEMARKET_REVIEW;


------------------------------------------- 승환 유저 테이블 생성코드 
DROP TABLE USER;

CREATE TABLE TB_USER
(
    USER_ID VARCHAR2(30) ,
    PASSWORD VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH DATE,
    GENDER CHAR,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(50),
    NICKNAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30),
    CREATE_ACCOUNT_DATE DATE DEFAULT SYSDATE,
    DELETE_ACCOUNT_YN CHAR DEFAULT 'N' CHECK(DELETE_ACCOUNT_YN IN ('Y','N')) NOT NULL,
    IS_ADMIN VARCHAR2(10) DEFAULT 'USER' CHECK(IS_ADMIN IN ('ADMIN','USER')),
    GRADE VARCHAR2(10) DEFAULT 'SILVER',
    USER_IMG VARCHAR2(500),
    USER_INFO VARCHAR2(1000),
    
    CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID)
);  
------------------------------------------- 승환 유저 테이블 생성코드



CREATE TABLE SITTER(
    SITTER_CODE NUMBER PRIMARY KEY,
    SITTER_TITLE VARCHAR2(200) NOT NULL,
    SITTER_LOC VARCHAR2(200) NOT NULL,
    SITTER_PRICE INT NOT NULL,
    SITTER_DESC VARCHAR2(500),
    SITTER_IMG VARCHAR2(300),
    USER_ID VARCHAR2(100)
);

CREATE TABLE SITTER_REVIEW(
    SITTER_REVIEW_CODE NUMBER PRIMARY KEY,
    SITTER_REVIEW_DESC VARCHAR(300),
    SITTER_REVIEW_RATINGS INT,
    USER_ID VARCHAR2(100),
    SITTER_CODE NUMBER
);

CREATE TABLE FREEMARKET(
    FREEMARKET_CODE NUMBER PRIMARY KEY,
    FREEMARKET_TITLE VARCHAR2(200) NOT NULL,
    FREEMARKET_LOC VARCHAR2(200) NOT NULL,
    FREEMARKET_PRICE INT NOT NULL,
    FREEMARKET_DESC VARCHAR2(500),
    FREEMARKET_IMG VARCHAR2(300),
    USER_ID VARCHAR2(100)
);

CREATE TABLE FREEMARKET_REVIEW(
    FREEMARKET_REVIEW_CODE NUMBER PRIMARY KEY,
    FREEMARKET_REVIEW_DESC VARCHAR(300),
    FREEMARKET_REVIEW_RATINGS INT,
    USER_ID VARCHAR2(100),
    FREEMARKET_CODE NUMBER
);

CREATE SEQUENCE SEQ_SITTER;
CREATE SEQUENCE SEQ_SITTER_REVIEW;
CREATE SEQUENCE SEQ_FREEMARKET;
CREATE SEQUENCE SEQ_FREEMARKET_REVIEW;

ALTER TABLE SITTER_REVIEW ADD CONSTRAINT SITTER_REVIEW_SITTER_CODE_FK FOREIGN KEY(SITTER_CODE) REFERENCES SITTER;
ALTER TABLE FREEMARKET_REVIEW ADD CONSTRAINT FREEMARKET_CODE_FK FOREIGN KEY(FREEMARKET_CODE) REFERENCES FREEMARKET;

-------------------------------------------------------------------------------------------------------------주연테이블
DROP TABLE ANNOUNCEMENT;
DROP TABLE EVENT;
CREATE TABLE ANNOUNCEMENT (
 ANNOUNCEMENT_CODE NUMBER PRIMARY KEY,
 USER_ID VARCHAR2(100),
 ANNOUNCEMENT_CREATE_TIME VARCHAR2(100) NOT NULL,
 ANNOUNCEMENT_VIEWS NUMBER,
 ANNOUNCEMENT_CONTENTS VARCHAR2(1000)
);

CREATE TABLE EVENT(
 EVENT_CODE NUMBER PRIMARY KEY,
 USER_ID VARCHAR2(100),
 EVENT_DATE VARCHAR2(100) NOT NULL,
 EVENT_CONTENTS VARCHAR2(1000),
 EVENT_LINK_ADDRESS VARCHAR2(500)
);

CREATE SEQUENCE EVENT_SEQ;
CREATE SEQUENCE ANNOUNCEMENT_SEQ;

ALTER TABLE ANNOUNCEMENT ADD CONSTRAINT ANNOUNCEMENT_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES USER;
ALTER TABLE EVENT ADD CONSTRAINT EVENT_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES USER;
---------------------------------------------------------------------------------------------------------------주연테이블
