DROP TABLE SITTER_REVIEW;
DROP TABLE FREEMARKET_REVIEW;
DROP TABLE SITTER;
DROP TABLE FREEMARKET;
DROP SEQUENCE SEQ_SITTER;
DROP SEQUENCE SEQ_SITTER_REVIEW;
DROP SEQUENCE SEQ_FREEMARKET;
DROP SEQUENCE SEQ_FREEMARKET_REVIEW;


------------------------------------------- 승환 유저 테이블 생성코드 
DROP TABLE USER;

CREATE TABLE TB_USER
(
    USER_ID VARCHAR2(30) ,
    PASSWORD VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH DATE,
    GENDER CHAR,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(50),
    NICKNAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30),
    CREATE_ACCOUNT_DATE DATE DEFAULT SYSDATE,
    DELETE_ACCOUNT_YN CHAR DEFAULT 'N' CHECK(DELETE_ACCOUNT_YN IN ('Y','N')) NOT NULL,
    IS_ADMIN VARCHAR2(10) DEFAULT 'USER' CHECK(IS_ADMIN IN ('ADMIN','USER')),
    GRADE VARCHAR2(10) DEFAULT 'SILVER',
    USER_IMG VARCHAR2(500),
    USER_INFO VARCHAR2(1000),
    
    CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID)
);  
------------------------------------------- 승환 유저 테이블 생성코드



CREATE TABLE SITTER(
    SITTER_CODE NUMBER PRIMARY KEY,
    SITTER_TITLE VARCHAR2(200) NOT NULL,
    SITTER_LOC VARCHAR2(200) NOT NULL,
    SITTER_PRICE INT NOT NULL,
    SITTER_DESC VARCHAR2(500),
    SITTER_IMG VARCHAR2(300),
    USER_ID VARCHAR2(100)
);

CREATE TABLE SITTER_REVIEW(
    SITTER_REVIEW_CODE NUMBER PRIMARY KEY,
    SITTER_REVIEW_DESC VARCHAR(300),
    SITTER_REVIEW_RATINGS INT,
    USER_ID VARCHAR2(100),
    SITTER_CODE NUMBER
);

CREATE TABLE FREEMARKET(
    FREEMARKET_CODE NUMBER PRIMARY KEY,
    FREEMARKET_TITLE VARCHAR2(200) NOT NULL,
    FREEMARKET_LOC VARCHAR2(200) NOT NULL,
    FREEMARKET_PRICE INT NOT NULL,
    FREEMARKET_DESC VARCHAR2(500),
    FREEMARKET_IMG VARCHAR2(300),
    USER_ID VARCHAR2(100)
);

CREATE TABLE FREEMARKET_REVIEW(
    FREEMARKET_REVIEW_CODE NUMBER PRIMARY KEY,
    FREEMARKET_REVIEW_DESC VARCHAR(300),
    FREEMARKET_REVIEW_RATINGS INT,
    USER_ID VARCHAR2(100),
    FREEMARKET_CODE NUMBER
);

CREATE SEQUENCE SEQ_SITTER;
CREATE SEQUENCE SEQ_SITTER_REVIEW;
CREATE SEQUENCE SEQ_FREEMARKET;
CREATE SEQUENCE SEQ_FREEMARKET_REVIEW;

ALTER TABLE SITTER_REVIEW ADD CONSTRAINT SITTER_REVIEW_SITTER_CODE_FK FOREIGN KEY(SITTER_CODE) REFERENCES SITTER;
ALTER TABLE FREEMARKET_REVIEW ADD CONSTRAINT FREEMARKET_CODE_FK FOREIGN KEY(FREEMARKET_CODE) REFERENCES FREEMARKET;


-----------------------------------------------------------------------------------------------------------------------
--------------------------------------------- 예진&지우 테이블 ----------------------------------------------------------
DROP TABLE MEDIA;
DROP TABLE MEDIA_COMMENT;
DROP TABLE COMMON;
DROP TABLE COMMON_COMMENT;
DROP TABLE LOST;
DROP TABLE LOST_COMMENT;

DROP SEQUENCE SEQ_MEDIA;
DROP SEQUENCE MEDIA_COMMENT;
DROP SEQUENCE COMMON;
DROP SEQUENCE COMMON_COMMENT;
DROP SEQUENCE LOST;
DROP SEQUENCE LOST_COMMENT;


CREATE TABLE MEDIA(
 MEDIA_CODE NUMBER,
 NICKNAME VARCHAR2(200),
 MEDIA_TITLE VARCHAR2(300) NOT NULL,
 MEDIA_DATE DATE DEFAULT SYSDATE,
 MEDIA_VIEWS NUMBER DEFAULT 0,
 MEDIA_URL VARCHAR2(300) NOT NULL,
 MEDIA_DESC VARCHAR2(1000),
 MEDIA_REPORT_YN CHAR DEFAULT 'N' CHECK(MEDIA_REPORT_YN IN ('Y','N')) NOT NULL  ,
 MEDIA_CATEGORY VARCHAR2(200) ,
 USER_ID VARCHAR2(100)

);



CREATE TABLE MEDIA_COMMENT(
 M_COMMENT_CODE NUMBER,
 M_COMMENT_DESC VARCHAR2(500),
 M_COMMENT_DATE DATE DEFAULT SYSDATE,
 NICKNAME VARCHAR2(200),
 M_COMMENT_CODE_SUPER NUMBER,
 M_COMMENT_REPORT_YN CHAR DEFAULT 'N' CHECK(M_COMMENT_REPORT_YN IN ('Y','N')) NOT NULL,
 MEDIA_CODE NUMBER,
 USER_ID VARCHAR2(100)
);

CREATE TABLE COMMON(
 COMMON_CODE NUMBER,
 NICKNAME VARCHAR2(200),
 COMMON_DATE DATE DEFAULT SYSDATE,
 COMMON_VIEWS NUMBER DEFAULT 0,
 COMMON_TITLE VARCHAR2(300)NOT NULL,
 COMMON_DESC VARCHAR2(1000),
 COMMON_REPORT_YN CHAR DEFAULT 'N' CHECK(COMMOM_REPORT_YN IN ('Y','N')) NOT NULL,
 USER_ID VARCHAR2(100)
);


CREATE TABLE COMMON_COMMENT(
 C_COMMENT_CODE NUMBER,
 C_COMMENT_DESC VARCHAR2(500),
 C_COMMENT_DATE DATE DEFAULT SYSDATE,
 NICKNAME VARCHAR2(200),
 C_COMMENT_CODE_SUPER NUMBER,
 C_COMMENT_REPORT_YN CHAR DEFAULT 'N' CHECK(C_COMMENT_REPORT_YN IN ('Y','N')) NOT NULL,
 COMMON_CODE NUMBER,
 USER_ID VARCHAR2(100)
);

CREATE TABLE LOST(
 LOST_CODE NUMBER,
 NICKNAME VARCHAR2(200) ,
 LOST_TITLE VARCHAR2(300)NOT NULL,
 LOST_DATE DATE DEFAULT SYSDATE,
 LOST_VIEWS NUMBER DEFAULT 0,
 LOST_DESC VARCHAR2(1000),
 LOST_REPORT_YN CHAR DEFAULT 'N' CHECK(LOST_REPORT_YN IN ('Y','N')) NOT NULL,
 USER_ID VARCHAR2(100)
);



CREATE TABLE LOST_COMMENT(
 L_COMMENT_CODE NUMBER,
 L_COMMENT_DESC VARCHAR2(500),
 L_COMMENT_DATE DATE DEFAULT SYSDATE,
 NICKNAME VARCHAR2(200),
 L_COMMENT_CODE_SUPER NUMBER,
 L_COMMENT_REPORT_YN CHAR DEFAULT 'N' CHECK(F_COMMENT_REPORT_YN IN ('Y','N')) NOT NULL,
 LOST_CODE NUMBER,
 USER_ID VARCHAR2(100)
);


ALTER TABLE MEDIA ADD CONSTRAINT MEDIA_CODE_PK PRIMARY KEY(MEDIA_CODE);
ALTER TABLE MEDIA_COMMENT ADD CONSTRAINT M_COMMENT_PK PRIMARY KEY(M_COMMENT_CODE);
ALTER TABLE COMMON ADD CONSTRAINT COMMON_CODE_PK PRIMARY KEY(COMMON_CODE);
ALTER TABLE COMMON_COMMENT ADD CONSTRAINT C_COMMENT_CODE_PK PRIMARY KEY(C_COMMENT_CODE);
ALTER TABLE LOST ADD CONSTRAINT LOST_CODE_PK PRIMARY KEY(LOST_CODE);
ALTER TABLE LOST_COMMENT ADD CONSTRAINT L_COMMENT_CODE_PK PRIMARY KEY(L_COMMENT_CODE);

ALTER TABLE MEDIA ADD CONSTRAINT MEDIA_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE MEDIA_COMMENT ADD CONSTRAINT MEDIA_COMMENT_CODE_FK FOREIGN KEY(MEDIA_CODE)REFERENCES MEDIA;
ALTER TABLE MEDIA_COMMENT ADD CONSTRAINT MEDIA_COMMENT_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE COMMON ADD CONSTRAINT COMMON_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE COMMON_COMMENT ADD CONSTRAINT COMMON_COMMENT_CODE_FK FOREIGN KEY(COMMON_CODE)REFERENCES COMMON;
ALTER TABLE COMMON_COMMENT ADD CONSTRAINT COMMON_COMMENT_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE LOST ADD CONSTRAINT LOST_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE LOST_COMMENT ADD CONSTRAINT LOST_COMMENT_CODE_FK FOREIGN KEY (LOST_CODE)REFERENCES LOST;
ALTER TABLE LOST_COMMENT ADD CONSTRAINT LOST_COMMENT_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;

-- 기존에 객체가 이름을 사용하고 잇습니다. 오류 뜸 
CREATE SEQUENCE SEQ_MEDIA;
CREATE SEQUENCE SEQ_MEDIA_COMMENT;
CREATE SEQUENCE SEQ_COMMON;
CREATE SEQUENCE SEQ_COMMON_COMMENT;
CREATE SEQUENCE SEQ_LOST;
CREATE SEQUENCE SEQ_LOST_COMMENT;

