DROP TABLE SITTER_REVIEW;
DROP TABLE FREEMARKET_REVIEW;
DROP TABLE SITTER;
DROP TABLE FREEMARKET;
DROP SEQUENCE SEQ_SITTER;
DROP SEQUENCE SEQ_SITTER_REVIEW;
DROP SEQUENCE SEQ_FREEMARKET;
DROP SEQUENCE SEQ_FREEMARKET_REVIEW;


------------------------------------------- 승환 유저 테이블 생성코드 
DROP TABLE USER;

CREATE TABLE TB_USER
(
    USER_ID VARCHAR2(30) ,
    PASSWORD VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH DATE,
    GENDER CHAR,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(50),
    NICKNAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30),
    CREATE_ACCOUNT_DATE DATE DEFAULT SYSDATE,
    DELETE_ACCOUNT_YN CHAR DEFAULT 'N' CHECK(DELETE_ACCOUNT_YN IN ('Y','N')) NOT NULL,
    IS_ADMIN VARCHAR2(10) DEFAULT 'USER' CHECK(IS_ADMIN IN ('ADMIN','USER')),
    GRADE VARCHAR2(10) DEFAULT 'SILVER',
    USER_IMG VARCHAR2(500),
    USER_INFO VARCHAR2(1000),
    
    CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID)
);  
------------------------------------------- 승환 유저 테이블 생성코드



CREATE TABLE SITTER(
    SITTER_CODE NUMBER PRIMARY KEY,
    SITTER_TITLE VARCHAR2(200) NOT NULL,
    SITTER_LOC VARCHAR2(200) NOT NULL,
    SITTER_PRICE INT NOT NULL,
    SITTER_DESC VARCHAR2(500),
    SITTER_IMG VARCHAR2(300),
    USER_ID VARCHAR2(100)
);

CREATE TABLE SITTER_REVIEW(
    SITTER_REVIEW_CODE NUMBER PRIMARY KEY,
    SITTER_REVIEW_DESC VARCHAR(300),
    SITTER_REVIEW_RATINGS INT,
    USER_ID VARCHAR2(100),
    SITTER_CODE NUMBER
);

CREATE TABLE FREEMARKET(
    FREEMARKET_CODE NUMBER PRIMARY KEY,
    FREEMARKET_TITLE VARCHAR2(200) NOT NULL,
    FREEMARKET_LOC VARCHAR2(200) NOT NULL,
    FREEMARKET_PRICE INT NOT NULL,
    FREEMARKET_DESC VARCHAR2(500),
    FREEMARKET_IMG VARCHAR2(300),
    USER_ID VARCHAR2(100)
);

CREATE TABLE FREEMARKET_REVIEW(
    FREEMARKET_REVIEW_CODE NUMBER PRIMARY KEY,
    FREEMARKET_REVIEW_DESC VARCHAR(300),
    FREEMARKET_REVIEW_RATINGS INT,
    USER_ID VARCHAR2(100),
    FREEMARKET_CODE NUMBER
);

CREATE SEQUENCE SEQ_SITTER;
CREATE SEQUENCE SEQ_SITTER_REVIEW;
CREATE SEQUENCE SEQ_FREEMARKET;
CREATE SEQUENCE SEQ_FREEMARKET_REVIEW;

ALTER TABLE SITTER_REVIEW ADD CONSTRAINT SITTER_REVIEW_SITTER_CODE_FK FOREIGN KEY(SITTER_CODE) REFERENCES SITTER;
ALTER TABLE FREEMARKET_REVIEW ADD CONSTRAINT FREEMARKET_CODE_FK FOREIGN KEY(FREEMARKET_CODE) REFERENCES FREEMARKET;


-----------------------------------------------------------------------------------------------------------------------
--------------------------------------------- 예진&지우 테이블 ----------------------------------------------------------
DROP TABLE MEDIA;
DROP TABLE MEDIA_LIKE;
DROP TABLE MEDIA_COMMENT;
DROP TABLE GENERALPOST;
DROP TABLE GENERALPOST_LIKE;
DROP TABLE GENERALPOST_COMMENT;
DROP TABLE FIND;
DROP TABLE FIND_LIKE;
DROP TABLE FIND_COMMENT;

DROP SEQUENCE SEQ_MEDIA_A;
DROP SEQUENCE SEQ_MEDIA_LIKE_A;
DROP SEQUENCE MEDIA_COMMENT;
DROP SEQUENCE GENERALPOST;
DROP SEQUENCE GENERALPOST_LIKE;
DROP SEQUENCE GENERALPOST_COMMENT;
DROP SEQUENCE FIND;
DROP SEQUENCE FIND_LIKE;
DROP SEQUENCE FIND_COMMENT;


CREATE TABLE MEDIA(
 MEDIA_CODE NUMBER,
 NICKNAME VARCHAR2(200),
 MEDIA_TITLE VARCHAR2(300) NOT NULL,
 MEDIA_DATE DATE DEFAULT SYSDATE,
 MEDIA_VIEWS NUMBER DEFAULT 0,
 MEDIA_URL VARCHAR2(300) NOT NULL,
 MEDIA_DESC VARCHAR2(500),
 MEDIA_REPORT_YN CHAR DEFAULT 'N' CHECK(MEDIA_REPORT_YN IN ('Y','N')) NOT NULL  ,
 MEDIA_CATEGORY VARCHAR2(200) ,
 USER_ID VARCHAR2(100)

);

CREATE TABLE MEDIA_LIKE(
 M_LIKE_CODE NUMBER,
 MEDIA_CODE NUMBER,
 USER_ID VARCHAR2(100)
  -- 마이페이지ID
 ); 

CREATE TABLE MEDIA_COMMENT(
 M_COMMENT_CODE NUMBER,
 M_COMMENT_DESC VARCHAR2(300),
 M_COMMENT_DATE DATE DEFAULT SYSDATE,
 NICKNAME VARCHAR2(200),
 --대댓글
 M_COMMENT_REPORT_YN CHAR DEFAULT 'N' CHECK(M_COMMENT_REPORT_YN IN ('Y','N')) NOT NULL,
 MEDIA_CODE NUMBER,
 USER_ID VARCHAR2(100)
);

CREATE TABLE GENERALPOST(
 GENERALPOST_CODE NUMBER,
 NICKNAME VARCHAR2(200),
 GENERALPOST_DATE DATE DEFAULT SYSDATE,
 GENERALPOST_VIEWS NUMBER DEFAULT 0,
 GENERALPOST_TITLE VARCHAR2(300)NOT NULL,
 GENERALPOST_DESC VARCHAR2(500),
 GENERALPOST_REPORT_YN CHAR DEFAULT 'N' CHECK(GENERALPOST_REPORT_YN IN ('Y','N')) NOT NULL,
 USER_ID VARCHAR2(100)
);

CREATE TABLE GENERALPOST_LIKE(
 G_LIKE_CODE NUMBER,
 GENERALPOST_CODE NUMBER,
 USER_ID VARCHAR2(100)
 -- 마이페이지ID
);

CREATE TABLE GENERALPOST_COMMENT(
 G_COMMENT_CODE NUMBER,
 G_COMMENT_DESC VARCHAR2(300),
 G_COMMENT_DATE DATE DEFAULT SYSDATE,
 NICKNAME VARCHAR2(200),
 --대댓글
 G_COMMENT_REPORT_YN CHAR DEFAULT 'N' CHECK(G_COMMENT_REPORT_YN IN ('Y','N')) NOT NULL,
 GENERALPOST_CODE NUMBER,
 USER_ID VARCHAR2(100)
);

CREATE TABLE FIND(
 FIND_CODE NUMBER,
 NICKNAME VARCHAR2(200) ,
 FIND_TITLE VARCHAR2(300)NOT NULL,
 FIND_DATE DATE DEFAULT SYSDATE,
 FIND_VIEWS NUMBER DEFAULT 0,
 FIND_DESC VARCHAR2(500),
 FIND_REPORT_YN CHAR DEFAULT 'N' CHECK(FIND_REPORT_YN IN ('Y','N')) NOT NULL,
 USER_ID VARCHAR2(100)
);

CREATE TABLE FIND_LIKE(
 F_LIKE_CODE NUMBER,
 FIND_CODE NUMBER,
 USER_ID VARCHAR2(100)
 -- 마이페이지ID
);

CREATE TABLE FIND_COMMENT(
 F_COMMENT_CODE NUMBER,
 G_COMMENT_DESC VARCHAR2(300),
 G_COMMENT_DATE DATE DEFAULT SYSDATE,
 NICKNAME VARCHAR2(200),
 --대댓글
 F_COMMENT_REPORT_YN CHAR DEFAULT 'N' CHECK(F_COMMENT_REPORT_YN IN ('Y','N')) NOT NULL,
 FIND_CODE NUMBER,
 USER_ID VARCHAR2(100)
);


ALTER TABLE MEDIA ADD CONSTRAINT MEDIA_CODE_PK PRIMARY KEY(MEDIA_CODE);
ALTER TABLE MEDIA_LIKE ADD CONSTRAINT M_LIKE_PK PRIMARY KEY(M_LIKE_CODE);
ALTER TABLE MEDIA_COMMENT ADD CONSTRAINT M_COMMENT_PK PRIMARY KEY(M_COMMENT_CODE);
ALTER TABLE GENERALPOST ADD CONSTRAINT GENERALPOST_CODE_PK PRIMARY KEY(GENERALPOST_CODE);
ALTER TABLE GENERALPOST_LIKE ADD CONSTRAINT G_LIKE_CODE_PK PRIMARY KEY(G_LIKE_CODE);
ALTER TABLE GENERALPOST_COMMENT ADD CONSTRAINT G_COMMENT_CODE_PK PRIMARY KEY(G_COMMENT_CODE);
ALTER TABLE FIND ADD CONSTRAINT FIND_CODE_PK PRIMARY KEY(FIND_CODE);
ALTER TABLE FIND_LIKE ADD CONSTRAINT F_LIKE_CODE_PK PRIMARY KEY(F_LIKE_CODE);
ALTER TABLE FIND_COMMENT ADD CONSTRAINT F_COMMENT_CODE_PK PRIMARY KEY(F_COMMENT_CODE);

ALTER TABLE MEDIA ADD CONSTRAINT MEDIA_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE MEDIA_LIKE ADD CONSTRAINT MEDIA_LIKE_CODE_FK FOREIGN KEY(MEDIA_CODE)REFERENCES MEDIA;
ALTER TABLE MEDIA_LIKE ADD CONSTRAINT MEDIA_LIKE_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE MEDIA_COMMENT ADD CONSTRAINT MEDIA_COMMENT_CODE_FK FOREIGN KEY(MEDIA_CODE)REFERENCES MEDIA;
ALTER TABLE MEDIA_COMMENT ADD CONSTRAINT MEDIA_COMMENT_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE GENERALPOST ADD CONSTRAINT GENERALPOST_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE GENERALPOST_LIKE ADD CONSTRAINT GENERALPOST_LIKE_CODE_FK FOREIGN KEY(GENERALPOST_CODE)REFERENCES GENERALPOST;
ALTER TABLE GENERALPOST_LIKE ADD CONSTRAINT GENERALPOST_LIKE_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE GENERALPOST_COMMENT ADD CONSTRAINT GENERALPOST_COMMENT_CODE_FK FOREIGN KEY(GENERALPOST_CODE)REFERENCES GENERALPOST;
ALTER TABLE GENERALPOST_COMMENT ADD CONSTRAINT GENERALPOST_COMMENT_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE FIND ADD CONSTRAINT FIND_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE FIND_LIKE ADD CONSTRAINT FIND_LIKE_CODE_FK FOREIGN KEY (FIND_CODE)REFERENCES FIND;
ALTER TABLE FIND_LIKE ADD CONSTRAINT FIND_LIKE_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;
ALTER TABLE FIND_COMMENT ADD CONSTRAINT FIND_COMMENT_CODE_FK FOREIGN KEY (FIND_CODE)REFERENCES FIND;
ALTER TABLE FIND_COMMENT ADD CONSTRAINT FIND_COMMENT_ID_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER;

-- 기존에 객체가 이름을 사용하고 잇습니다. 오류 뜸 
CREATE SEQUENCE SEQ_MEDIA;
CREATE SEQUENCE SEQ_MEDIA_LIKE;
CREATE SEQUENCE SEQ_MEDIA_COMMENT;
CREATE SEQUENCE SEQ_GENERALPOST;
CREATE SEQUENCE SEQ_GENERALPOST_LIKE;
CREATE SEQUENCE SEQ_GENERALPOST_COMMENT;
CREATE SEQUENCE SEQ_FIND;
CREATE SEQUENCE SEQ_FIND_LIKE;
CREATE SEQUENCE SEQ_FIND_COMMENT;

